# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://elk.zone/kanoa.de/@dion"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "pixelfed"
name = "Pixelfed"
url = "https://pixelfed.de/i/web/profile/519178760679028649"

[social.params]
icon = "camera"