baseURL = "https://krinkko.github.io"
title = "krinkko's"
theme = "etch"
themesDir = "themes"
languageCode = "de-de"
defaultContentLanguage = "de"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
enableRobotsTXT = true
enableEmoji = true
paginate = 5

[params]
  description = "Braunschweig based sysadmin. Proud father of two and husband. I like hardcore punk, songwriters to rap. Open mind, open heart. LOVES bicycles <3"
  copyright = "© 2024 d381blog"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "archive"
    name = "archive"
    title = "archive"
    url = "/posts-archive/"
    weight = 30

  [[menu.second]]
    identifier = "impressum"
    name = "impressum"
    title = "impressum"
    url = "/impressum/"
    weight = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
